### ISSUE TITLE
Server side validations about natural numbers

### ISSUE THREAD

**Issue by arowM** [blueimpact/kucipong#108]
For example, if we submit coupon with reference price of -3000, back-end server does not warn about it even though all prices and percentage values have type of `Natural`.

**Comment by cdepillabout** [comment]
@arowM I was surprised that this was happening, but I realized that `Price`s are actually defined as `Int64`, not `Natural`.

I thought it might make sense to have a negative price in order to represent discounts.  For example, the price of a dinner could be `1000` yen, but if the user has a coupon for 200 yen off, it could be represented as `-200` yen.

However, currently it doesn't really seem like we are using this functionality, so what do you think about changing `Price` to be a `Natural`?

**Comment by arowM** [comment]
@cdepillabout 
It makes sense!

Though I am not confident that I fully understood the example you said, I think using `Natural` for `Price` does not have any problem even for the example because no one will use a coupon to pay more than original price. We just can use `200` instead of `-200` for that case.

**Comment by cdepillabout** [comment]
Okay, sounds good, I'll change `Int64` to `Natural`.
