### ISSUE TITLE
pseudo-type-safe templates with ede

### ISSUE THREAD

**Issue by cdepillabout** [blueimpact/kucipong#12]
@arowM I have a question about the pseudo type-safe templates.

``` haskell
-- Replace line 26 of `src/Kucipong/RenderTemplate.hs` with this.
renderTemplateFromEnv' :: forall a
                       . (Default a, ToObject a)
                       => Proxy a -> String -> Q Exp
renderTemplateFromEnv' _ filename = do
    ...
    let eitherParsedTemplate = eitherParse rawTemplate
    -- Check to make sure the template can be parsed correctly.  Return an
    -- error during compile time to the user if it cannot.
    void $ fromEitherM handleIncorrectTemplate eitherParsedTemplate
    -- Check to make sure the bindings are correct, i.e.,
    -- the types are correct and all variables required by template presence.
    -- Return an error during compile time to the user if it cannot.
    void $
      fromEitherM handleIncorrectBindings
        $ map (flip safeRender (def :: a)) eitherParsedTemplate
    ...


class ToObject a where
  toObject :: a -> Object

-- | A wrapper function to render from any 'ToObject` instance instead of 'Object' itself.
--   Also, it may be better to escape for html in this wrapper function.
safeRender :: (ToObject a)
        => Template -> a -> Result Text
safeRender templ = render templ . escapeHtml . toObject

escapeHtml :: Object -> Object
escapeHtml = undefined $ \c ->
  case c of
    '&' -> "&amp;"
    '\'' -> "&#x27;"
    '`' -> "&#x60;"
    '"' -> "&quot;"
    '<' -> "&lt;"
    '>' -> "&gt;"
```

I'm wondering about the use of this `ToObject` class.  Do you envision using this `ToObject` class for passing the real template values.

For instance, are you imagining something like this:

``` haskell
-- | This is the handler to show the login page for the admin.
loginPage
    :: forall ctx m
     . ( MonadIO m
       )
    => ActionCtxT ctx m ()
loginPage =
    $(renderTemplateFromEnv "adminUser_login.html") $
        AdminUserLoginPageTemplateValues
            { email = "foo@gmail.com"
            , userName = "Foo Bar"
            , failedLogin = False
            }

-- | This data type represents the template values that can be passed to the @adminUser_login.html@ template.
data AdminUserLoginPageTemplateValues = AdminUserLoginPageTemplateValues
    { email :: Text
    , userName :: Text
    , failedLogin :: Bool
    } deriving (Aeson.ToJSON)

instance ToObject AdminUserLoginPageTemplateValues where
    toObject :: AdminUserLoginPageTemplateValues -> Aeson.Object
    toObject = Aeson.toJSON

instance Default AdminUserLoginPageTemplateValues where
    def :: AdminUserLoginPageTemplateValues
    def = AdminUserLoginPageTemplateValues
        { email = "test@test.com", userName = "Test", failedLogin = False }
```

A very simplified version of `adminUser_login.html` would look something like this:

``` html
<p>{{ userName }}</p>
{% if failedLogin %}<p>You failed to login.</p>{% endif %}
<p>Email: {{ email }}</p>
```

We will have to create a new data type for every template.  However, we can probably automatically derive the `Default` and `ToObject` classes using either the `Generic` machinery or template haskell.

Do you think it's worth it creating a new datatype for every template?

Also, if we do this, we should use ghc-8 so that we can use `DuplicateRecordFields`.

**Comment by cdepillabout** [comment]
@arowM Also, feel free to work on this instead of #10 or #11.

**Comment by cdepillabout** [comment]
Also, it looks like `renderTemplateFromEnv'` is taking a `Proxy` in order to figure out the mapping between data type (like `AdminUserLoginPageTemplateValues`) and template name (like `adminUser_login.html`) in order to test rendering the template, but it might be possible (maybe even easier?) to use TypeFamilies for this.

It might even be worthwhile to create our own dsl for this, and just use template haskell to generate all the data types, type class instances, type families, etc.  Just like persistent does:

```
# Our dsl:
- template: "adminUser_login.html"
  - userName: Text
  - email: Text
  - failedLogin: Bool
- template: ...
```

**Comment by arowM** [comment]
@cdepillabout 
Please let me add more information about the role of the `renderTemplateFromEnv'` function and why I introduced `ToObject` class rather than simply use `Object`.

First, the role of the `renderTemplateFromEnv` is for pseudo type checking of the template variables.
I intended to use this function in compile time by template haskell, and check if the template file can be correctly rendered with given parameters.
To confirm that all parameters are given and types of them are all correct, I propose to give the dummy parameters of same types as given parameters.
If the render process with dummy parameters succeeded on compile time, the render process will not fail on run time.
That's why I gave the type of template variables as `Proxy` to the function and rendered the template with `def` dummy data.

Next, the reason why I did not directly use `Object` is that from `Object` type we cannot generate dummy value corresponding to the original type (e.g., Text, Bool, ...).
Since the `Object` type is defined as `type Object = HashMap Text Value`, let's see if we can unwrap the `Value` and get original type.
The code bellow tries to unwrap the `Value` and get `defaultValue` from undefined value.

``` haskell
import           Data.Aeson.Types (Value (..), toJSON)

main :: IO ()
main = do
  print (defaultValue (toJSON b :: Value))
 where
  b = undefined :: Bool

defaultValue :: Value -> Value
defaultValue (Bool _) = Bool True
defaultValue _ = undefined
```

This code can be compiled, but causes `undefined` error on run time.
It seems it is because the `Value` parameter in aeson package is defined strictly as follows.

``` haskell
-- | A JSON value represented as a Haskell value.
data Value = Object !Object
           | Array !Array
           | String !Text
           | Number !Scientific
           | Bool !Bool
           | Null
             deriving (Eq, Read, Show, Typeable, Data)
```

This is because I used `ToObject a => a` rather than simply use `Object` value to check the type on compile time.

> Do you think it's worth it creating a new datatype for every template?

It seems to cost too much to get the benefit of type checking on compile time, as you say.
Now I propose another way to check types.
How about using something like `Data.Aeson.Lazy` exposing following lazy version of `Value` and `toStrict` function.

``` haskell
import Data.Aeson.Types as SAeson

-- | A JSON value represented as a Haskell value.
data Value = Object Object
           | Array Array
           | String Text
           | Number Scientific
           | Bool Bool
           | Null
             deriving (Eq, Read, Show, Typeable, Data)

toStrict :: Value -> SAeson.Value
toStrict (Object o) = SAeson.Object !o
toStrict (Array a) = SAeson.Array !a
...
```

If we have this lazy version of `Value`, it is possible to use lazy version of `Object` on `renderTemplateFromEnv'`.

```
import Data.Aeson.Lazy.Types as LAeson

renderTemplateFromEnv' :: LAeson.Object -> String -> Q Exp
renderTemplateFromEnv' o filename = do
  ...
 where
  dummyObj = map (LAeson.toStrict . LAeson.defaultValue) o
```

I'll do this on this weekend.
Of course, this pseudo type check mechanism is just a test process with dummy template values (e.g, If the template file has a variable only in specific `if` statement, we can miss it on compile time!), but in future we can implement true type-check system on EDE using lazy version of `Object`.

**Comment by cdepillabout** [comment]
@arowM Can we close this for now?

Maybe at some point in the future it would be nice to either use something like `haiji` or shakespeare templates.

**Comment by arowM** [comment]
OK, I'll close this.
memo: #35 is related this issue.

**Comment by cdepillabout** [comment]
Thanks!
