### ISSUE TITLE
how to handle the BusinessCategoryDetail in /store/edit

### ISSUE THREAD

**Issue by cdepillabout** [blueimpact/kucipong#54]
In the PR #53, I'm not sure how to handle the `businessCategoryDetail` column for the `Store`.

@arowM How do you think we should store this in the database?

**Comment by arowM** [comment]
@cdepillabout As I've mentioned about it partly in my comment on #53, I propose to store it as a `List` like object.
The actual way to store it in DB is up to you; I guess it would be the one of bellow.

a. Make the type of `businessCategoryDetail` from `Text` to `[Text]`
    \* It seems much better to identify it by ID rather than its display name, though the `Text` may already mean ID  
b. Remove the businessCategoryDetail column from `Store` table and add another table to manage businessCategoryDetail list of a store

**Comment by cdepillabout** [comment]
@arowM How many different business categories are possible?  Do we ever want to be able to search by business category detail?

If not, then it might work to just keep them as `[Text]` (as implemented in #53).  If we want to be able to search by specific business category details, it might be a good idea to store them in a different table.

To be honest, I'm not sure I understand the difference between a business category and a business category detail.  Could you give an example of a business category and a business category detail?

Looking at the documentation, it looks like business categories might be things like:

- グルメ
- ファッション
- ガジェット
- 旅行
- 美容

Then, for a business category of "グルメ", the business category details should be things like this?

- 焼肉
- 日本食
- 寿司
- 広々とした店内


Also, where should we store the master list of business category details (and business categories)?  If it is in the database, it could be dynamically expandable by the admin users.  We could also just hard code them (in either the frontend or the backend).  That might be slightly easier.

**Comment by arowM** [comment]
@cdepillabout 
> How many different business categories are possible?

I'm not sure actually, and I guess it will be also added after publishing service.

> Do we ever want to be able to search by business category detail?

Yes, the business category detail must be used in the API to search recommended coupons for end users.

> where should we store the master list of business category details (and business categories)?

Though the changes of available business category details will happen often, there are less need to store them in the database.
It is because the user who decide to change them is somebody belongs to BlueImpact, and it means that it is easy to tell us to change the hard coded relations.

> To be honest, I'm not sure I understand the difference between a business category and a business category detail.

The big difference between business category and business category detail is that

* End users can filter recommended coupons by __business category__ in the category page
* End user can not explicitly filter recommended coupons by __business category detail__
    * Though they can specify them indirectly by choosing only one business category detail at initial set up phase
    * Ideally it is better to recommend not only coupons having chose business category detail but also any related coupons not having them
* Business category details are divided to two types

    * Some belong to a business category
    (e.g., 焼き肉 belongs to グルメ)

    * Others can be a subcategory of any category
    (e.g., 広々とした店内 belongs to any category)

It seems that we should have an API to get business category details belonging to specified business category.

**Comment by arowM** [comment]
And in development phase, let's use temporary business category details without thinking much.

**Comment by arowM** [comment]
I noticed that we do not need to make an API to get business category details but we can do well by editing store edit page template.
I'll PR for that after enabling to use `heterocephalus` template.

**Comment by cdepillabout** [comment]
Can this be closed by #63?

**Comment by arowM** [comment]
It sounds good.
